[pull] master from jitsi:master (#4)
* feat(video-quality): Always prioritize SS in tile view.

* fix(lang) update french translation

* fix(lang) update German translation

Signed-off-by: Christoph Settgast <csett86@web.de>

* fix(lang) update Arabic translation

* fix(lang) update Occitan translation

* fix(lang) update Russian translation

* fix(prejoin) Fix prejoin app

* fix(rn,welcome-page) don't create video track unnecessarily

We are no longer rendering it, so skip creating it altogether and make sure it's
destroyed on meeting end.

* fix(Avatar): Display correctly any emoji/special character in a avatar initials

* fix(rn,sdk) remove deprecated color scheme prop

It has been non-functional for a while.

* fix(rn,sdk) drop deprecated option enableWelcomePage

It got replaced by a feature flag.

* chore(breakout-rooms) Added analytics (#10421)

* fix(linguistics) Use 'email' instead of 'e-mail'

* feat(ui) updateTheme helper for client branding

* feat(ui) reverted tokens updates

* chore(deps) lib-jitsi-meet@latest

* fix(TPC): Select 1 as the default scale factor for p2p. This fixes an issue where a user is not able to unmute their video if the MediaStreamTrack associated with the camera stream returns a null value for the track height.
* Save track source name to JitsiRemoteTrack

https://github.com/jitsi/lib-jitsi-meet/compare/bdfbb82087ce2a9336157da35e739fb4b250ed66...a1c966058c0c0e721ba72e5d170919db3ab02fdf

* fix: Updates the default value of rtcstatsEnabled to match the code. (#10425)

* fix(filmstrip) remove border from filmstrip (#10367)

* fix(rn, participants-pane) Show raised hand indicator (#10424)

Make name container limited width and add ellipsis text overflow

Show raise hand status live in participants pane

* feat)rn,sdk) introduce a "ready to close" event

This event is the event host applications need to listen to for knowing when to
dispose the SDK from now on.

Since the introduction of breakout rooms it's possible that we navigate from one
meeting to another, so there will be several conference join / terminations.

In addition, local track destruction is now moved to SET_ROOM when there is no
room, aka, we are going back to the welcome page or to the black page.

* fix(TileViewButton) fix on mobile

`setOverflowMenuVisible` doesn't exist on mobile.

* fix(android) fixes error in BroadcastEvent

* feat(notifications) revisit timeouts and make them configurable

* fix(breakout-rooms) fix error in case main room is no longer available

* fix(breakout-rooms) simplify code

* fix(breakout-rooms) avoid accessing invalid room objects

* fix(breakout-rooms) cleanup code

* fix(lang) update translations for Catalan

* chore(deps) lib-jitsi-meet@latest (#10436)

feat: Enables the moderator to {dis/en}able bridge-side rtcstats.

https://github.com/jitsi/lib-jitsi-meet/pull/1789
https://github.com/jitsi/lib-jitsi-meet/commit/0261073faf9ab5ba03cb3ca9299c3b14b269a421

* feat(load-test): Unmute video.

* fix(lang) update German translation

* chore(rn,deps) react-native-webrtc@1.94.0

* fix(android) set facebook groupId for all react-native dependencies

* fix(config) add transcribingEnabled to whitelist

Fixes: https://github.com/jitsi/jitsi-meet/issues/10326

* chore(deps) lib-jitsi-meet@latest

* fix(breakout-rooms) send whole payload on update event

https://github.com/jitsi/lib-jitsi-meet/compare/0261073faf9ab5ba03cb3ca9299c3b14b269a421...f4f7db2e5f4c815a2c5e1bc4de44f0e16e1d27a6

* fix(breakout-rooms) make sure the default name is monotonically increasing

* feat(conference) UI updates for mobile navigation bar (#10437)

* feat(conference) updated native navigation bar and toolbox styles

* feat: (speaker-stats) add speaker stats feature to native

* fix(breakout-rooms) Improve breakout rooms

Don't show more menu on the main room

Fix join room on mobile web

When moving to room reset breakout rooms state to avoid showing incorrect data before response from prosody is received

* fix(lang) update Polish translation

* fix(lang) update Polish translation

* feat(branding) added native extension to updateTheme helper

* fix(lint) fix all eslint warnings

* feat(lint) treat warnings as errors

* fix(ios) avoid creating CXProvider objects when CallKit is disabled

Co-authored-by: Saúl Ibarra Corretgé <saghul@jitsi.org>

* fix(external-api) send AUDIO_MUTED_CHANGED event only when value changed

* feat(rtcstats): send facial expressions to rtcstats-server (#10461)

* send facial expressions to rtcstats

* remove comment

* remove extra line

* fix(breakout-rooms) fix operations when inside a breakout room

Fix not being able to create / remove breakout rooms when the moderator is
inside a breakout room.

* fix(rn,settings) only show "disable call integration" on Android

It;';s not implemented on iOS.

* fix(breakout-rooms) fix checking if a user is in a room

Breakout rooms are just reserved UUIDs, they need not exist as actual MUCs,
until a participant joins. Thus, take this into account when checking if a
participant is in a room.

* feat(config) defaultLocalDisplayName and defaultRemoteDisplayName

* fix(share-video): stop video from the participant list

* feat: Enables muc rate limit for lobby and breakout muc components.

* feat: Add disableBeforeUnloadHandlers option

* chore(deps) lib-jitsi-meet@latest

* feat: Handle disableBeforeUnloadHandlers option.
* feat(conference) Implement audio/video mute disable when sender limit is reached. Jicofo sends a presence when the audio/video sender limit is reaced in the conference. The client can then proceed to disable the audio and video mute buttons when this occurs.

https://github.com/jitsi/lib-jitsi-meet/compare/f4f7db2e5f4c815a2c5e1bc4de44f0e16e1d27a6...6b3d3d278362a7a30afe112c7f98200f7b209bfd

* fix(conference) remove dead code

Went for a different approach, this code is dead now.

* fix(conference) simplify code

Unify the 2 functions used to leave the room into a single one.

* fix(breakout-rooms) disable lobby in breakout rooms

The main room lobby gets diverted to the rooms, things can get confusing. We
might need to revisit this in the future.

* fix(breakout-rooms) disable recording and live-streaming

There is currently no way to directly join a breakout room, so Jibri won't know
what to do. This shall be revisited in the future.

* fix(breakout-rooms) fix no video when coming back to main room

Re-create local tracks so we have a clean state.

* fix: Fixes correct state in lobby screen on wrong password.

Fixes #9869.

* Revert "fix(Prejoin): Make prejoin name noneditable only when taken from jwt"

This reverts commit af7c31682714da80f5dfac002923ec6cc090a3d8.

* feat(conference) Implement audio/video mute disable when sender limit is reached.

* feat(conference) Impl audio/video mute disable when sender limit is reached.
Jicofo sends a presence when the audio/video sender limit is reached in the conference. The client can then proceed to disable the audio and video mute buttons when this occurs.

* squash: use a different action type and show notification.

* fix(gravatar): Add crossOrigin attribute.

In cross origin issolated mode we need to explicitly add crossOrigin
attribute for all resources that are loaded with CORS headers.

* fix(lang) update German translation

* fix(breakout-rooms) fix when using tenants

* fix(modal) remove dead code

* fix(conference) fix broken dispatch on mobile

* fix(etherpad) fix loading Etherpad on web

Fixes: https://github.com/jitsi/jitsi-meet/issues/10486

* fix(participants) fix unpinning when switching conferences

* New strings translated

So to be up to date

* fix(etherpad) fix Etherpad closing when dominant speaker changes

Fixes: https://github.com/jitsi/jitsi-meet/issues/8109

* fix(breakout-rooms) make sure participants in breakout rooms have a display name

* fix(dropbox): OAuth to use postMessage.

* feat: (speaker-stats) fix refresh and minor refactoring

* fix(rn,breakout-rooms) wait for the room to be left

Just like on web, we wait for the current room to be left in order to avoid all
kinds of problems.

* fix(rn,external-api) remove dead code

* feat(notifications) coalesce participant left and raised hand notifications

* fix(lang) update french translation + fix 2 existing translations

* fix(breakout-rooms) mark function as async

Not all code paths return a Promise, make sure it does.

* fix(rn,conference) hide timer until it has started

It may never start if the component is not deployed.

* chore(deps) lib-jitsi-meet@latest

* fix(ChatRoom) make sure we wait for all promises on leave()
* fix(ChatRoom) make sure EMUC is destroyed
* fix(JitsiConference) make sure RTC is always destroyed
* fix(log) don't log full stanzas
* fix(avmoderation,breakout-rooms) dispose handlers when leaving

https://github.com/jitsi/lib-jitsi-meet/compare/6b3d3d278362a7a30afe112c7f98200f7b209bfd...61aef9083551436bbc1155df52ec9b553c16e65f

* feat(tile-view): allow disabling thumbnail enlargement

* chore(deps) lib-jitsi-meet@latest

* fix(JitsiConference) properly handle leave() errors

https://github.com/jitsi/lib-jitsi-meet/compare/61aef9083551436bbc1155df52ec9b553c16e65f...9e5d83f4aceb9f922583c871d933e97ee2b05753

* fix(rn,navbar) fix invalid boolean check

`startTimestamp` is not a boolean, so make sure we return one.

* feat(breakout-rooms) add notification when joining rooms

* fix(screen-sharing, picture-in-picture) re-enables PIP after stopping screen-share

* feat: (moderate-reaction-sounds) enable moderator to mute reaction sounds

* fix(lang) update German translation

* fix(lang) update french translation

* feat(external-api): enhance recordingLinkAvailable to provide ttl info

* fix(rn,chat): Fix chat and polls title

* fix(breakout-rooms) fix not waiting to leave the room

We need to wait for it before we start joining.

* fix(breakout,av-moderation): support non-ascii room names

rooms are created in prosody in their urlencoded form, eg täst
becomes t%c3%a4st@conference.jitsi.example.org

As local params = formdecode(query) contains an urldecode, we
need to reencode the room name so that the room can be found in
prosody.

Closes: #10525
Signed-off-by: Christoph Settgast <csett86@web.de>

* fix(breakout,av-moderation): support non-ascii tenant names

Same applies to tenant names as it applies to room names, as the
tenants/subdomains are prefixed to the room names in prosody.

Signed-off-by: Christoph Settgast <csett86@web.de>

* fix(media) dispatch the unmute blocked action irrepective of the muted state.
This fixes an issue where the user muted by focus is able to unmute themselves even when the sender limit has been reached.

* fix(lang) update Arabic translation

* fix(facial-expressions) load worker as a blob

* fix(lang) update Portuguese translation

* feat(prejoin) Add possibility to hide extra join options buttons (#10434)

* fix(lang) update Traditional Chinese (Taiwan) translation

* fix(lang) update sv translation

* fix(participants-list): Avoid ui moving on input focus

* feat(end-meet-for-all) Trigger notifyReadyToClose event on end meetin… (#10549)

* fix(virtual-backgrounds) fix error if we failed to load the model

If another try is made, show an error notification instead of failing with an
exception.

* fix(virtual-backgrounds) make error message translatable

* fix(screenshot-capture) Update screenshot capture feature (#10443)

* fix(screenshot-capture) Update screenshot capture feature

Add participants jid list to request

Enable screenshot capture only when recording is also on

Updated interval

* chore(rn) updates react-native-webrtc

* chore(deps) lib-jitsi-meet@latest

* fix(tpc) disable ulpfec on chrome 96 (jitsi/lib-jitsi-meet#1816)
* fix: Fixes call to _setTrackMuteStatus.
* Refactor presence update (jitsi/lib-jitsi-meet#1814)

https://github.com/jitsi/lib-jitsi-meet/compare/9e5d83f4aceb9f922583c871d933e97ee2b05753...e9e37099a143c06355f9e6868bbcdf20b48583b1

* fix(overflow-drawer) Only use overflow drawer on mobile

* fix(breakout-rooms) fix non-functional context menu

Close the menu after sending a participant to a breakout room, that will detach
the context menu from the current participant and it will work properly when
they join back.

* fix(rn) join conference if started by moderator

Issue was that APP is not defined at this place on mobile,
thus this raising ReferenceError which caused the waitForOwner to break

Closes: #10211

* fix(breakout-rooms) cleanup remote tracks when a conference is left

* feat(self-view) Added ability to hide self view

Added config option disableSelfView. This disables it on web and native

Added button on local video menu and toggle in settings on web to change the setting

* fix(screenshot-capture) Use feature on web only

Fixes broken native

* fix(android) fix NoClassDefFoundError for Landroid/graphics/ColorSpace

Fixes: https://github.com/jitsi/jitsi-meet/issues/10182

* chore(deps) lib-jitsi-meet@latest (#10566)

* fix(browser-capabilities) expose supported mobile browsers

https://github.com/jitsi/lib-jitsi-meet/compare/e9e37099a143c06355f9e6868bbcdf20b48583b1...161da84ac045afd8ac8eed9168bd708dc0cbedb1

* fix(browser-compatibility) hide launch in web for unsupported mobile browsers (#10569)

* fix(notifications) Create web middleware (#10568)

Fixes broken native

* fix(lang) update Catalan translation

Co-authored-by: Payetus <payet91@gmail.xom>

* feat(chat) keyboard covering input on android fix

* feat(tracks) Clean up the track if a source addition is rejected. (#10562)

* feat(tracks) Clean up the track if a source addition is rejected.
When jicofo rejects a source-add because of sendder limits, dispose and remove the local track from the conference.

* chore(deps) update LJM to latest.

* fix(breakout-rooms) cleanup local tracks when a conference is left.

* fix(shortcuts) Ignore keyboard shortcuts when the button are disabled.

* fix(notifications) Adjust the timeout for unmute blocked notifications.

* chore(rn,versions) bump app and sdk versions

* fix(rn,breakout-rooms) fix not rendering display names

* fix(disableSelfView) Fix issue with remote participant video (#10582)

Fix issue where last participant is shown as inactive when the self view is hidden

* fix(tracks) fix disposing of local tracks

Don't just clear the storage for them, local tracks must be disposed, in order
for RN capturer to be freed for example.

* fix(rn,breakout-rooms) create desired local tracks when joining rooms

* fix(breakout-rooms) ensure we use the same media types when joining

Only audio and video are considered. Screen sharing won't be preserved.

* typo fix

dekstopAudioStream --> desktopAudioStream

* feat(index.html): Add fonts.html SSI.

* feat(security) created SecurityOptions React Navigation screen (#10509)

* feat(security) Security Options screen

* chore(deps) lib-jitsi-meet@latest

* fix(presence): Do not sent presence if there is no active media session.
* fix: server-side callstats is never enabled (#1823)
* fix(JitsiConference) squelch bogus p2p session end error

https://github.com/jitsi/lib-jitsi-meet/compare/8aa35dae401f32a7eafe2b7dec159827c4bb2a84...8a95fda2593b91d51d2e048f447e19627c6ec0fb

* feat(media) Disable desktopshare when the video sender limit is reached.

* chore(deps) lib-jitsi-meet@latest

* fix: Fixes set effect and correct presence state.

https://github.com/jitsi/lib-jitsi-meet/compare/8a95fda2593b91d51d2e048f447e19627c6ec0fb...d630bc32a1262afd0432d8b8d8d0025dd5afd1e5

* fix(lang) update German translation

* fix(rn) fix broken mobile build

Importing the entire feature triggers web UI imports.

* feat(i18n): Allow label rewrite via advanced branding

* fix(Polls): Calculate vote percentage based on total number of votes

Percentage was previously calculated based on number of voters

* fix(overflow-menu) Pin reactions on menu bottom on mobile web (#10599)

Move some styles from SCSS to JSS

* fix(speaker-stats): prevent search from closing when enter pressed and from keeping previous state (#10597)

* fix(speaker-stats): prevent search from closing when enter pressed and from keeping previous state

* fix(speaker-stats): remove unnecessary blank lines

* fix(speaker-stats): add empty dependencies to prevent dismiss callback

* add(speaker-stats): reset search criteria action

* feat(profile-settings): Hide email field under profile settings

* fix: Fixes disable moderation sounds in meeting. (#10604)

* fix: Fixes disable moderation sounds in meeting.

Moderators in the meeting were sending presence update after one moderator turn it on, which even my result a inconsistent state and flipping the state between moderators several times.

* squash: Adds option to disable reaction moderation.

* fix(Avatar): Fix initials when avatar contains multiple special characters

* fix(Prejoin): Allow changing 'Enable pre meeting screen' option while prejoin screen visible

* fix(config.js) Added missing participant left notification key.

* fix(overflow-menu) Use fixed height only on drawer (#10612)

* fix: Respects disable reactions moderation flag for popups.

* fix: Use default remote display name in speaker stats when one is missing.

* fix(lang) update Dutch translations

Co-authored-by: Jaya Allamsetty <jaya.allamsetty@8x8.com>
Co-authored-by: gpatel-fr <44170243+gpatel-fr@users.noreply.github.com>
Co-authored-by: csett86 <csett86@web.de>
Co-authored-by: Ali Alhaidary <75235623+ali-alhaidary@users.noreply.github.com>
Co-authored-by: Mejans <61360811+Mejans@users.noreply.github.com>
Co-authored-by: Greg Galperin <ggalperin@bloomberg.net>
Co-authored-by: hmuresan <horatiu.muresan@8x8.com>
Co-authored-by: Saúl Ibarra Corretgé <saghul@jitsi.org>
Co-authored-by: Vlad Piersec <vlad.piersec@8x8.com>
Co-authored-by: Robert Pintilii <robert.pin9@gmail.com>
Co-authored-by: Calin Chitu <calinte2002@yahoo.co.uk>
Co-authored-by: George Politis <gp@jitsi.org>
Co-authored-by: Avram Tudor <tudor.potecaru@gmail.com>
Co-authored-by: titus.moldovan <titus.moldovan@8x8.com>
Co-authored-by: Tudor D. Pop <tudor.dan.pop7@gmail.com>
Co-authored-by: Payetus <payet91@gmail.com>
Co-authored-by: Hristo Terezov <hristo@jitsi.org>
Co-authored-by: tmoldovan8x8 <62697631+tmoldovan8x8@users.noreply.github.com>
Co-authored-by: Andrei Oltean <andi.oltean@gmail.com>
Co-authored-by: Szymon Ruciński <44577190+szymonrucinski@users.noreply.github.com>
Co-authored-by: Alex Bumbu <alex.bumbu@8x8.com>
Co-authored-by: Andrei Gavrilescu <51706180+andrei-gavrilescu@users.noreply.github.com>
Co-authored-by: Mihaela Dumitru <mihdmt@gmail.com>
Co-authored-by: Дамян Минков <damencho@jitsi.org>
Co-authored-by: Jaya Allamsetty <54324652+jallamsetty1@users.noreply.github.com>
Co-authored-by: Jasper Hugo <jasper@jasperhugo.com>
Co-authored-by: Gabriel Borlea <gabi.borlea.1@gmail.com>
Co-authored-by: José Luís Andrade <32515675+jluisfa@users.noreply.github.com>
Co-authored-by: Horatiu Muresan <39557534+horymury@users.noreply.github.com>
Co-authored-by: SiderealArt <nelson22768384@gmail.com>
Co-authored-by: JH <75114843+BustaFu@users.noreply.github.com>
Co-authored-by: Payetus <payet91@gmail.xom>
Co-authored-by: Rokixy <48944401+Rokixy@users.noreply.github.com>
Co-authored-by: Calinteodor <calin.chitu@8x8.com>
Co-authored-by: Ashiq Hassan <ashiqhassan95@gmail.com>